import type {Pet,Entry} from './life-sync';
export type Session={access_token:string;refresh_token:string;expires_in:number;expires_at?:number;user:{id:string;email?:string}};
let session:Session|null=null;
const base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
export const configured=!!(base&&key);
const sessionKey='life-sync-auth:'+base;
function keepSession(value:Session){session={...value,expires_at:value.expires_at||Math.floor(Date.now()/1000)+value.expires_in};try{sessionStorage.setItem(sessionKey,JSON.stringify(session));}catch{}return session;}
let refreshing:Promise<Session|null>|null=null;
async function refresh(){if(!session)return null;if(refreshing)return refreshing;refreshing=(async()=>{const result=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session!.refresh_token})},false);return keepSession(result);})();try{return await refreshing;}finally{refreshing=null;}}
export async function restoreSession(){if(!configured)return null;try{const raw=sessionStorage.getItem(sessionKey);if(!raw)return null;const saved=JSON.parse(raw);if(!saved.access_token||!saved.refresh_token||!saved.user?.id)return null;session=saved;if(!saved.expires_at||saved.expires_at<=Date.now()/1000+60)await refresh();return session;}catch{session=null;try{sessionStorage.removeItem(sessionKey);}catch{}return null;}}
async function ensureSession(){if(!session)throw Error('ログインしてください。');if((session.expires_at||0)<=Date.now()/1000+60)await refresh();}

async function request(path:string,opts:RequestInit={},authorized=true):Promise<any>{if(!configured)throw Error('Supabaseが未接続です。設定手順をご確認ください。');if(authorized)await ensureSession();const res=await fetch(base+path,{...opts,headers:{apikey:key,'Content-Type':'application/json',...(authorized&&session?{Authorization:'Bearer '+session.access_token}:{}),...opts.headers}});if(!res.ok){const data:any=await res.json().catch(()=>({}));throw Error(data.msg||data.message||data.error_description||'通信に失敗しました。時間をおいて再試行してください。');}const body=await res.text();return body.trim()?JSON.parse(body):null;}
export async function authenticate(mode:string,email:string,password:string){const path=mode==='register'?'/auth/v1/signup':mode==='reset'?'/auth/v1/recover':'/auth/v1/token?grant_type=password';const result=await request(path,{method:'POST',body:JSON.stringify(mode==='reset'?{email}:{email,password})},false);if(result?.access_token){return keepSession(result);}return null;}
export async function signout(){if(session)await request('/auth/v1/logout',{method:'POST'});session=null;try{sessionStorage.removeItem(sessionKey);}catch{}}
export async function load(){if(!session)throw Error('ログインしてください。');const [p,e]=await Promise.all([request('/rest/v1/pets?select=id,data&order=created_at.asc'),request('/rest/v1/entries?select=id,pet_id,data&order=created_at.desc')]);return {pets:p.map((r:any)=>({...r.data,id:r.id})),entries:e.map((r:any)=>({...r.data,id:r.id,petId:r.pet_id}))};}
export async function save(type:'pets'|'entries',item:Pet|Entry){if(!session)throw Error('ログインしてください。');const body={id:item.id,user_id:session.user.id,data:item,...(type==='entries'?{pet_id:(item as Entry).petId}:{})};await request('/rest/v1/'+type+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(body)});}
export async function remove(type:'pets'|'entries',id:string){await request('/rest/v1/'+type+'?id=eq.'+encodeURIComponent(id),{method:'DELETE'});}
export async function upload(file:File){await ensureSession();if(!session)throw Error('ログインしてください。');if(file.size>25*1024*1024)throw Error('1ファイル25MBまで保存できます。');if(!/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|quicktime)|application\/pdf)$/.test(file.type))throw Error('JPEG・PNG・WebP・GIF・MP4・WebM・MOV・PDFに対応しています。');const path=session.user.id+'/'+crypto.randomUUID();const res=await fetch(base+'/storage/v1/object/pet-media/'+path,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+session.access_token,'Content-Type':file.type},body:file});if(!res.ok)throw Error('添付ファイルの保存に失敗しました。');return {path,type:file.type};}
export async function mediaUrl(path:string){if(path==='sample')return '/pet.jpg';const r=await request('/storage/v1/object/sign/pet-media/'+path,{method:'POST',body:JSON.stringify({expiresIn:3600})});return base+'/storage/v1'+r.signedURL;}
